# File: nginx-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: project1
  source:
    # Replace with your actual Git repo URL
    repoURL: 'https://github.com/shreyassureshrao/manifest-code.git'  
    # Replace with the actual path in your repository
    path: 'nginx-deployment.yaml'  
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
